server:
  port: 8089

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: true

  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: auth
      schemaAction: CREATE_IF_NOT_EXISTS


